services:
  claude:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-Asia/Tokyo}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    user: node
    volumes:
      - claude-code-bashhistory:/commandhistory
      - claude-code-config:/home/node/.claude
      - ./setup/CLAUDE.md:/home/node/.claude/CLAUDE.md
      - ./workspace:/workspace
    working_dir: /workspace
    environment:
      NODE_OPTIONS: --max-old-space-size=4096
      CLAUDE_CONFIG_DIR: /home/node/.claude
      POWERLEVEL9K_DISABLE_GITSTATUS: "true"
    env_file:
      - .env
    command: /usr/local/bin/init-claude-mcp.sh
    tty: true
    depends_on:
      - taskmaster

  taskmaster:
    image: node:20
    volumes:
      - ./workspace:/workspace
    working_dir: /workspace
    environment:
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
    command: npx -y task-master-ai --transport sse --port 4891
    ports:
      - "4891:4891"

volumes:
  claude-code-bashhistory:
  claude-code-config: