version: '3'

tasks:
  up:
    desc: "Dockerコンテナを起動"
    cmds:
      - docker compose up -d
  
  down:
    desc: "Dockerコンテナを停止"
    cmds:
      - docker compose down
  
  restart:
    desc: "Dockerコンテナを再起動"
    cmds:
      - docker compose down
      - docker compose up -d

  exec:
    desc: "Dockerコンテナ内でコマンドを実行"
    cmds:
      - docker compose exec claude zsh